[build]
  base = "car-hire-main123/car-hire-main"
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NPM_FLAGS = "--include=dev"
  NODE_VERSION = "18"

[context.production]
  environment = { NODE_ENV = "production" }
